### ISSUE TITLE
コメントアウトがもっとあるといいと思います。たとえば、関数の説明とかがあるともっと分かりやすいです。

### ISSUE THREAD

**Issue by MinamiSawamura** [c0a21051d1/ProjExD#12]
https://github.com/c0a21051d1/ProjExD/blob/a9e84d70334c4fec711a47a6bcf86c851b89e162/ex03/maze.py#L5

**Comment by c0a21051d1** [comment]
指摘ありがとうございます。コメントアウトいれました。
