### ISSUE TITLE
if文の処理について

### ISSUE THREAD

**Issue by MinamiSawamura** [c0a21051d1/ProjExD#14]
https://github.com/c0a21051d1/ProjExD/blob/4ec53674fe579565cd8cfdf20b8182b98962dee6/ex04/dodge_bomb.py#L80
速度が２倍になる処理で、同じif文で値が違うという処理を行っているので、何か変数を１つ容易してkey_dct[pg.K_bがTrueになったらその変数の値を変更し、Falseだったら元の値に戻す処理をした方がif文が少なくなって良いと思います。

**Comment by c0a21051d1** [comment]
ご指摘ありがとうございます。今後の参考にしたいと思います。
