### ISSUE TITLE
倍速について

### ISSUE THREAD

**Issue by c0a2113791** [c0a21051d1/ProjExD#17]
https://github.com/c0a21051d1/ProjExD/blob/fa31d00a2419e7fb27a417f25dfa669703f97fe0/ex04/dodge_bomb.py#L99
倍速はこうかとんだけにしたほうがいいかも

**Comment by c0a21051d1** [comment]
指摘ありがとうございます。操作はしやすいようにしたつもりでしたが、貴重な意見としてとらえます
