### ISSUE TITLE
ボールが一個しか反応しないです

### ISSUE THREAD

**Issue by ghost** [c0a21051d1/ProjExD#19]
https://github.com/c0a21051d1/ProjExD/blob/7674a3e68bc55841273a09622da6dbd2ffe08ffa/ex05/dodge_bomb.py#L112

ボールの当たり判定が一個しかないです。

**Comment by c0a21051d1** [comment]
magenta以外の色のボールの判定が無い原因がよくわからなかったので直せませんでした。
