### ISSUE TITLE
ファイル名などなど

### ISSUE THREAD

**Issue by c0a2113791** [c0a21051d1/ProjExD#21]
https://github.com/c0a21051d1/ProjExD/blob/7674a3e68bc55841273a09622da6dbd2ffe08ffa/ex05/dodge_bomb.py#L1
提出ファイル名が違うのと特定の色の爆弾しか反応しないです

**Comment by c0a21051d1** [comment]
ファイル名なおしました。
特定の色以外が反応しない原因がわからなかったため直せてないです。指摘ありがとうございます
