### ISSUE TITLE
funcの中に”C"が入っているのに使われていないので使った方がいいと思います。Cを押すとCがそのまま出力されます。

### ISSUE THREAD

**Issue by c0a2113935** [c0a21051d1/ProjExD#5]
https://github.com/c0a21051d1/ProjExD/blob/ae69cae1d2e1f7c62dbcfd57119272c80590273c/ex02/calc.py#L20

**Comment by c0a21051d1** [comment]
一文字削除がむずかしかったため代わりに　" . "（小数点）を追加しました。
