### ISSUE TITLE
高さと改行について

### ISSUE THREAD

**Issue by MinamiSawamura** [c0a21051d1/ProjExD#6]
https://github.com/c0a21051d1/ProjExD/blob/ae69cae1d2e1f7c62dbcfd57119272c80590273c/ex02/calc.py#L35
電卓を表示させたときの高さが少しあまっていたので、「root.geometry」の値を変更してボタンと高さを合わせた方が綺麗に見える。３行以上の改行はなくて良いと思った。１行、２行の方が見やすい

**Comment by c0a21051d1** [comment]
高さはすぐに変えることが可能だったため調整しました。
改行の数はすぐに対処できなかったためできてないです。
