### ISSUE TITLE
平方根について

### ISSUE THREAD

**Issue by c0a2113791** [c0a21051d1/ProjExD#7]
https://github.com/c0a21051d1/ProjExD/blob/ae69cae1d2e1f7c62dbcfd57119272c80590273c/ex02/calc.py#L11
別のボタンの設定を作成して、defでクリックした際の動きを記入するのがいいと思います。
平方根はmathをインポートしてmath.sqrt(int(入力式))で計算してくれると思います。
例）
定義（平方根の計算）
def click_sqrt(event):
    siki = entry.get()
    ans = math.sqrt(int(siki))
    entry.delete(0, tk.END)#表示された文字の削除
    entry.insert(tk.END, ans)

ボタンの設定
button_sq = tk.Button(root, text="√",width=4,height=2,font=(" ",30))
button_sq.grid(row=任意の場所 ,column=任意の場所)
button_sq.bind("<1>",click_sqrt)

**Comment by c0a21051d1** [comment]
空いてるスペースがないためこの変更をするとなると配置をまた変える必要がありそうなので残り時間では対処できないと判断しました。あとでやってみようと思います。
